### ISSUE TITLE
Hidden tests for puzzles

### ISSUE THREAD

**Issue by DaQuirm** [21-23/_qd#7]
So that players can't use the `reduce` trick or similar hacks.
Would involve project-wide changes (DB puzzle schema, QDP, etc.)
- [x] zandbak (v3.1.0, https://github.com/21-23/zandbak/commit/e860c41ee570f1e0471e3a15f6c7d62613809493)
- [x] zandbak-service (v2.1.0, https://github.com/21-23/zandbak-service/commit/99b40421e9ed2d403f4bc902d9492eb4c62251b3)
- [x] redemption
- [x] front-end service (no changes)
- [x] _qd UI (https://github.com/21-23/_qd-ui/commit/ec627d2e9bbf52d1b586a629a4bc54653cab13b2)
- [x] message factory (v5.2.2 https://github.com/21-23/message-factory/commit/0a30e54274773cb948729b1c2e6649b70f7d1bad)
- [x] _qd init puzzles (https://github.com/Shastel/_qd-secret/pull/4)
- [x] ignition (no changes)
- [x] _qd wiki (protocol)
- [x] qdp

**Comment by DaQuirm** [comment]
Looks like this one is well done: time to take it off the grill and serve on a plate! 🍽

**Comment by zemlanin** [comment]
Tried to solve "God save the Queen" with `_.reduce` over an `{}` and could not understand why _qd didn't accept my answer :(
